### ISSUE TITLE
Can't access the lower part of the screen because the push-up menu

### ISSUE THREAD

**Issue by Ingvix** [marcellodgl/harbour-vncscreen#3]
I can't access windows start menu, for example, with VNCScreen as the bottom of the remote desktop seems to be alligned with the push-up menu's bottom and not it's top.  I can only get it to show but the push-up menu activates at the same time so I can't press anything on the remote screen until I get off the menu but the remote screen also scrolls up with the menu.

Anyway, I think the push-up menu would be better if you could activated it anywhere  with two finger gesture or something so you could start typing without going to the bottom of the screen.

**Comment by marcellodgl** [comment]
Correction image size on Pinch area
