### ISSUE TITLE
Publish to chum?

### ISSUE THREAD

**Issue by poetaster** [marcellodgl/harbour-vncscreen#4]
Would you be willing to have the releases generated/distributed on chum?

**Comment by poetaster** [comment]
I forked an did a test with minor spec changes: https://build.merproject.org/project/show/home:poetaster:vnc

**Comment by marcellodgl** [comment]
Ok

**Comment by marcellodgl** [comment]
Thanks

**Comment by poetaster** [comment]
Thank you!
